version: '3.8'

services:
  pdf-doc-generator:
    container_name: pdf-doc-builder
    build: .
    ports:
      - "8092:8095"
    restart: unless-stopped
    # Limites otimizados para ALTA DEMANDA
    deploy:
      resources:
        limits:
          memory: 3G        # Aumentado para suportar mais browsers
          cpus: '2.0'       # Mais CPU para processamento paralelo
        reservations:
          memory: 1.5G      # Reserva maior para estabilidade
          cpus: '1.0'       
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=1024
      - PORT=8095                # alinhar porta interna com EXPOSE/health
      - QUEUE_TIMEOUT=45000      # timeout dedicado para fila
      - PREWARM_ENABLED=true
      - PREWARM_COUNT=4          # ajuste conforme CPU (2 vCPU -> 3~4 browsers)
      - MAX_CONCURRENT_BROWSERS=6    # 6 browsers simultâneos  
      - MAX_PAGES_PER_BROWSER=8      # 8 páginas por browser = 48 slots
      - BROWSER_TIMEOUT=25000        # Timeout reduzido para 25s
      - PAGE_TIMEOUT=15000           # Timeout de página reduzido
      - ENABLE_PAGE_POOL=true        # Pool de páginas ativo
      - MAX_PAGE_POOL=20             # 20 páginas reutilizáveis
      - CACHE_ENABLED=true           # Cache ativo
      - MAX_REQUESTS_PER_MINUTE=300  # 5 req/segundo
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      # Configurações anti-zombie processes
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
    # Configuração de health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s   # Playwright demora mais para inicializar
    # Logs otimizados
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Configurações de segurança
    security_opt:
      - seccomp:unconfined  # Necessário para Chromium
    shm_size: '2gb'         # CRÍTICO: Evita problemas de memória compartilhada
